apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: instana
  namespace: instana-clickhouse
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 2
        shardsCount: 4
      name: local
      schemaPolicy:
        replica: None
        shard: None
      templates:
        podTemplate: clickhouse
    files:
      config.d/storage.xml: |
        <clickhouse>
          <storage_configuration>
            <disks>
              <default/>
              <cold_disk>
                <path>/var/lib/clickhouse-cold/</path>
              </cold_disk>
            </disks>
            <policies>
              <logs_policy>
                <volumes>
                  <data>
                    <disk>default</disk>
                  </data>
                  <cold>
                    <disk>cold_disk</disk>
                  </cold>
                </volumes>
              </logs_policy>
              <logs_policy_v4>
                <volumes>
                  <tier1>
                    <disk>default</disk>
                  </tier1>
                  <tier2>
                    <disk>cold_disk</disk>
                  </tier2>
                </volumes>
              </logs_policy_v4>
            </policies>
          </storage_configuration>
        </clickhouse>
    profiles:
      default/allow_experimental_analyzer: "0"
      default/allow_experimental_database_replicated: 1
      default/background_pool_size: 32
      default/background_schedule_pool_size: 32
      default/distributed_directory_monitor_batch_inserts: 1
      default/distributed_directory_monitor_split_batch_on_failure: 1
      default/enable_http_compression: 1
      default/insert_distributed_sync: 1
      default/joined_subquery_requires_alias: 0
      default/load_balancing: random
      default/log_queries: 1
      default/log_query_views: 1
      default/max_execution_time: 100
      default/max_memory_usage: 10000000000
      default/max_query_size: 1048576
      default/max_threads: 16
      default/use_uncompressed_cache: 0
    quotas:
      default/interval/duration: 3600
      default/interval/errors: 0
      default/interval/execution_time: 0
      default/interval/queries: 0
      default/interval/read_rows: 0
      default/interval/result_rows: 0
    settings:
      max_concurrent_queries: 200
      max_partition_size_to_drop: 0
      max_table_size_to_drop: 0
      remote_servers/all-replicated/secret: clickhouse-default-pass
      remote_servers/all-sharded/secret: clickhouse-default-pass
      remote_servers/local/secret: clickhouse-default-pass
    users:
      clickhouse-user/networks/ip: ::/0
      clickhouse-user/password: clickhouse-default-pass
      default/password: clickhouse-default-pass
    zookeeper:
      nodes:
      - host: instana-zookeeper-headless.instana-clickhouse
  defaults:
    templates:
      dataVolumeClaimTemplate: instana-clickhouse-data-volume
      logVolumeClaimTemplate: instana-clickhouse-log-volume
      serviceTemplate: service-template
  license:
    accept: true
  templates:
    podTemplates:
    - name: clickhouse
      spec:
        containers:
        - command:
          - clickhouse-server
          - --config-file=/etc/clickhouse-server/config.xml
          image: registrymirror.tools.pci.tsys.aws/sre/instana/clickhouse-openssl:24.3.12.75-1-lts-ibm
          imagePullPolicy: IfNotPresent
          name: instana-clickhouse
          resources:
            requests:
              cpu: 1500m
              memory: 44Gi
          volumeMounts:
          - mountPath: /var/lib/clickhouse-cold/
            name: instana-clickhouse-cold-volume
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/sh
          - -c
          - --
          image: registrymirror.tools.pci.tsys.aws/sre/instana/clickhouse-openssl:24.3.12.75-1-lts-ibm
          imagePullPolicy: IfNotPresent
          name: clickhouse-log
        imagePullSecrets:
        - name: instana-registry
        securityContext:
          fsGroup: 0
          runAsGroup: 0
          runAsUser: 1001
    serviceTemplates:
    - name: service-template
      spec:
        ports:
        - name: http
          port: 8123
        - name: tcp
          port: 9000
    volumeClaimTemplates:
    - name: instana-clickhouse-data-volume
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 750Gi
        storageClassName: gp3-encrypted
    - name: instana-clickhouse-cold-volume
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: gp3-encrypted
    - name: instana-clickhouse-log-volume
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi
        storageClassName: gp3-encrypted
