apiVersion: instana.io/v1beta2
kind: Core
metadata:
  namespace: instana-core
  name: instana-core

spec:
  imageConfig:
    registry: registry
    tag: tag

  imagePullPolicy: IfNotPresent

  imagePullSecrets:
  - name: pullsecret

  #serviceAccountAnnotations:

  #priorityClassName:

  acceptors:
    agent:
      host: agent-acceptor.base-domain
      port: 443
    eum:
      host: eum.base-domain
      port: 443
    otlp:
      grpc:
        host: otlp-grpc.base-domain
        port: 443
      http:
        host: otlp-http.base-domain
        port: 443
    serverless:
      host: serverless.base-domain
      port: 443
    synthetics:
      host: synthetics.base-domain
      port: 443

  autoscalingEnabled: false

  baseDomain: baseDomain

  resourceProfile: small

  storageConfigs:
    rawSpans:
      pvcConfig:
        accessModes: 
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: rwx_storageclass
      #s3Config:
      #gcloudConfig:

    synthetics:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: rwx_storageclass
      #s3Config:
      #gcloudConfig:

    syntheticsKeystore:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass
      #s3Config:
      #gcloudConfig:

    eumSourceMaps:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass
      #s3Config:
      #gcloudConfig:

  #heapDumpsPVC:

  datastoreConfigs:
    cassandraConfigs:
      - hosts:
          - instana-cassandra-service.instana-cassandra.svc
        ports:
          - name: tcp
            port: 9042
        #properties: 
        authEnabled: true
        #keyspaces: []
        datacenter: cassandra
        #replicationFactor: 1

    clickhouseConfigs:
      - hosts: []
        ports:
          - name: tcp
            port: 9000
          - name: http
            port: 8123
        #properties:
        authEnabled: true
        #schemas:
        clusterName: local

    elasticsearchConfig:
      hosts:
        - instana-es-http.instana-elasticsearch.svc
      ports: 
        - name: tcp
          port: 9300
        - name: http
          port: 9200
      #properties:
      authEnabled: true
      clusterName: instana
      #defaultIndexShards: 5
      #defaultIndexReplicas: 0
      #defaultIndexRoutingPartitionSize: 2
      #indexConfigs: []

    kafkaConfig:
      hosts:
        - instana-kafka-bootstrap.instana-kafka.svc
      ports: 
        - name: tcp
          port: 9092
      #properties:
      authEnabled: true
      #replicationFactor: 1
      # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
      saslMechanism: SCRAM-SHA-512

    beeInstanaConfig:
      hosts:
        - aggregators.beeinstana.svc
      ports:
        - name: tcp
          port: 9998
      #properties:
      authEnabled: true
      clustered: true

    postgresConfigs:
      - hosts:
          - postgres-rw.instana-postgres.svc
        ports:
          - name: tcp
            port: 5432
        #properties:
        authEnabled: true
        #databases: []

  gatewayConfig:
    controller:
      config: {}
      imageConfig:
        registry: artifact-public.instana.io
        repository: infrastructure
        tag: tag
      replicas: 1
      tlsCipherSuites: []
    enabled: true
    gateway:
      adminListener: 0.0.0.0
      circuitBreakers:
        maxConnections: 50000
        maxPendingRequests: 50000
        maxRequests: 50000
        maxRetries: 4
      config: {}
      imageConfig:
        registry: artifact-public.instana.io
        repository: self-hosted-images/k8s
        tag: tag
      logLevel: error
      replicas: 1

  componentConfigs:
  - name: acceptor
    replicas: 2
    resources:
      limits:
        memory: 7124Mi
      requests:
        cpu: 877m
        memory: 7060Mi
  - name: accountant
    replicas: 1
    resources:
      limits:
        memory: 4348Mi
      requests:
        cpu: 351m
        memory: 4348Mi
  - name: appdata-health-aggregator
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: appdata-health-processor
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 702m
        memory: 4371Mi
  - name: appdata-reader
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: appdata-writer
    replicas: 4
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 1316m
        memory: 4371Mi
  - name: butler
    replicas: 1
    resources:
      limits:
        memory: 4348Mi
      requests:
        cpu: 351m
        memory: 4348Mi
  - name: cashier-ingest
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: cashier-rollup
    replicas: 2 
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: eum-acceptor
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: eum-health-processor
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 702m
        memory: 4371Mi
  - name: eum-processor
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 702m
        memory: 4371Mi
  - name: gateway
    replicas: 1
    resources:
      limits:
        memory: 4348Mi
      requests:
        cpu: 702m
        memory: 4348Mi
  - name: groundskeeper
    replicas: 1
    resources:
      limits:
        memory: 4348Mi
      requests:
        cpu: 702m
        memory: 4348Mi
  - name: js-stack-trace-translator
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: serverless-acceptor
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 877m
        memory: 4371Mi
  - name: sli-evaluator
    replicas: 2
    resources:
      limits:
        memory: 4421Mi
      requests:
        cpu: 702m
        memory: 4371Mi
  - name: ui-client
    replicas: 1
    resources:
      limits:
        memory: 955Mi
      requests:
        cpu: 351m
        memory: 841Mi
  - name: tag-processor
    replicas: 1
    resources:
      limits:
        memory: 4500Mi
      requests:
        cpu: 1
        memory: 4500Mi
      
  - name: log-processor
  - name: log-reader
  - name: log-writer

  deploymentStrategyType: RollingUpdate

  emailConfig:
    smtpConfig:
      from: from@example.com
      host: smtp.example.com
      port: 465
      useSSL: false
      startTLS: false
      check_server_identity: false
    #sesConfig:

  serviceProviderConfig:
    basePath: "/auth"
    maxIDPMetadataSizeInBytes: 200000
    maxAuthenticationLifetimeSeconds: 604800

  #proxyConfig:

  #geoDbUrl:

  featureFlags:
    - name: feature.logging.enabled
      enabled: false
    - name: feature.beeinstana.infra.metrics.enabled
      enabled: false
    - name: feature.infra.smart.alerts.enabled
      enabled: false
    - name: feature.automation.enabled
      enabled: false
    - name: feature.synthetics.enabled
      enabled: false
    - name: feature.kubecost.enabled
      enabled: false
    - name: feature.pcf.enabled
      enabled: false
    - name: feature.vsphere.enabled
      enabled: false
    - name: feature.openstack.enabled
      enabled: false
    - name: feature.phmc.enabled
      enabled: false
    - name: feature.powervc.enabled
      enabled: false
    - name: feature.zhmc.enabled
      enabled: false
    - name: feature.business.observability.enabled
      enabled: false
    - name: feature.assistme.enabled
      enabled: false

  #env:

  properties:
    - name: retention.metrics.rollup5
      value: 1
    - name: retention.metrics.rollup60
      value: 1
    - name: retention.metrics.rollup300
      value: 1
    - name: retention.metrics.rollup3600
      value: 1
    - name: retention.metrics.rawPayload
      value: 1
    - name: config.appdata.shortterm.retention.days
      value: 1
    - name: config.synthetics.retention.days
      value: 1
    - name: config.url.format.pathStyle
      value: "false"

  #nodeSelector:

  #tolerations:

  operationMode: normal
