apiVersion: instana.io/v1beta2
kind: Core

metadata:
  namespace: instana-core
  name: instana-core

spec:
  imageConfig:
    registry: artifact-public.instana.io
    repository: backend
    tag: tag

  imagePullPolicy: IfNotPresent

  imagePullSecrets:
    - name: image-pull-secret

#  serviceAccountAnnotations:
#    keys: ""
#    values: ""

#  priorityClassName: default

  baseDomain: base.domain

  # + 293
  acceptors:
    agent:
      host: agent-acceptor.base.domain
      port: 443
    eum:
      host: base.domain
      port: 443
    otlp:
      grpc:
        host: otlp-grpc.base.domain
        port: 443
      http:
        host: otlp-http.base.domain
        port: 443
    serverless:
      host: base.domain
      port: 443
    synthetics:
      host: base.domain
      port: 443

  # + 293
  # https://community.ibm.com/community/user/blogs/rishikesh-nair/2025/04/17/
  # migrating-from-nginx-to-envoy-in-instana-self-host
  gatewayConfig:
    enabled: true

    controller:
      config: {}
      imageConfig:
        registry: artifact-public.instana.io
        repository: infrastructure
        tag: 1.3.0
      replicas: 1
      tlsCipherSuites: []

    gateway:
      adminListener: 127.0.0.1
      circuitBreakers:
        maxConnections: 50000
        maxPendingRequests: 50000
        maxRequests: 50000
        maxRetries: 4
      config: {}
      imageConfig:
        registry: artifact-public.instana.io
        repository: self-hosted-images/k8s
        tag: 1.33.1_v0.7.0
      logLevel: error
      replicas: 1

  # + 293, beta
  autoscalingEnabled: false

  resourceProfile: small

  storageConfigs:
    rawSpans:
      pvcConfig:
              pvcConfig:
        accessModes: 
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: rwx_storageclass

    synthetics:
            pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass

    syntheticsKeystore:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass

    eumSourceMaps:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass

  heapDumpsPVC:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: rwx_storageclass

  datastoreConfigs:
    cassandraConfigs:
      - hosts:
          - instana-cassandra-service.instana-cassandra.svc
        ports:
          - name: tcp
            port: 9042
        #properties: {}
        authEnabled: true
        #keyspaces: []
        datacenter: cassandra
        replicationFactor: 1

    clickhouseConfigs:
      - hosts: []
        ports:
          - name: tcp
            port: 9000
          - name: http
            port: 8123
        #properties: {}
        authEnabled: true
        #schemas: []
        clusterName: local

    elasticsearchConfig:
      hosts:
        - instana-es-http.instana-elasticsearch.svc
      ports: 
        - name: tcp
          port: 9300
        - name: http
          port: 9200
      #properties: {}
      authEnabled: true
      clusterName: instana
      defaultIndexShards: 5
      defaultIndexReplicas: 0
      defaultIndexRoutingPartitionSize: 2
      #indexConfigs: []

    kafkaConfig:
      hosts:
        - instana-kafka-bootstrap.instana-kafka.svc
      ports: 
        - name: tcp
          port: 9092
      #properties: {}
      authEnabled: true
      replicationFactor: 1
      # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
      saslMechanism: SCRAM-SHA-512

    beeInstanaConfig:
      hosts:
        - aggregators.beeinstana.svc
      ports:
        - name: tcp
          port: 9998
      #properties:
      authEnabled: true
      clustered: true

    postgresConfigs:
      - hosts:
          - postgres-rw.instana-postgres.svc
        ports:
          - name: tcp
            port: 5432
        #properties: {}
        authEnabled: true
        #databases: []

#  componentConfigs:
#    - name: name
#      disabled: false
#      imageTag: tagoverwrite
#      replicas: 1
#      envs: []
#      resources:
#        limits:
#        requests:
#      autoscalingConfig: {}
#      affinity: {}
#      nodeSelector: {}
#      tolerations: []
#      priorityClassName: default
#      properties: {}

  deploymentStrategyType: RollingUpdate

  emailConfig:
    smtpConfig:
      from: from
      host: host
      port: port
      useSSL: true
      startTLS: true
      check_server_identity: false

#    sesConfig:
#      from: from
#      returnPath: path
#      region: region

  serviceProviderConfig:
    basePath: "/auth"
    maxIDPMetadataSizeInBytes: 200000
    maxAuthenticationLifetimeSeconds: 604800

#  proxyConfig:
#    host: host
#    port: port
#    nonProxyHosts: []

#  geoDbUrl: https://geodb.url.com

  agentAcceptorConfig:
    host: host
#    port: port

  # optional features
  featureFlags:

    - name: feature.beeinstana.infra.metrics.enabled
      enabled: true

    - name: feature.infra.smart.alerts.enabled
      enabled: true

    - name: feature.logging.enabled
      # logging uses clickhouse schema "logs". use a separate clickhose cluster or host
      # smart alerts for logs from instana tracers
      # unbounded analytics for logs from instana tracers
      # licensed logging features: extended log retention,
      # general log ingestion, log volume ingestion
      enabled: true

    - name: feature.automation.enabled
      enabled: true

    - name: feature.synthetics.enabled
      # configure: synthetics, syntheticsKeystore
      enabled: true

    - name: feature.kubecost.enabled
      # kubecost infra dashboard
      enabled: false

    - name: feature.pcf.enabled
      # tanzu infra dashboard
      enabled: false

    - name: feature.vsphere.enabled
      # vshpere infra dashboard
      enabled: false

    - name feature.openstack.enabled
      # openstack infra dashboard
      enabled: false

    - name: feature.phmc.enabled
      # ibm power hmc infra dashboard
      enabled: false

    - name: feature.powervc.enabled
      # ibm power vc infra dashboard
      enabled: false

    - name: feature.zhmc.enabled
      # ibm z hmc infra dashboard
      enabled: false

    - name: feature.business.observability.enabled
      enabled: false

    - name: feature.assistme.enabled
      # get answers button
      enabled: false

    - name: feature.kubernetes.horizontal.pod.autoscaler.enable
      # enabled by default
      enabled: true

#  env:

  properties:
    - name: retention.metrics.rollup5
      value: 86400

#  nodeSelector:
#    keys: ""
#    values: ""

#  tolerations: []

  operationMode: normal
