apiVersion: instana.io/v1beta2
kind: Core
metadata:
  namespace: instana-core
  name: instana-core

spec:
  imageConfig:
    registry: registry
    tag: tag

  imagePullPolicy: IfNotPresent

  imagePullSecrets:
  - name: pullsecret

  serviceAccountAnnotations:

  priorityClassName:

  baseDomain: baseDomain

  resourceProfile: small

  storageConfigs:
    rawSpans:
      pvcConfig:
        accessModes: 
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
        storageClassName: rwx_storageclass
      s3Config:
      gcloudConfig:

    synthetics:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: rwx_storageclass
      s3Config:
      gcloudConfig:

    syntheticsKeystore:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass
      s3Config:
      gcloudConfig:

    eumSourceMaps:
      pvcConfig:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: rwx_storageclass
      s3Config:
      gcloudConfig:

  heapDumpsPVC:

  datastoreConfigs:
    cassandraConfigs:
      - hosts:
          - instana-cassandra-service.instana-cassandra.svc
        ports:
          - name: tcp
            port: 9042
        #properties: 
        authEnabled: true
        #keyspaces: []
        datacenter: cassandra
        replicationFactor: 1

    clickhouseConfigs:
      - hosts: []
        ports:
          - name: tcp
            port: 9000
          - name: http
            port: 8123
        #properties:
        authEnabled: true
        #schemas:
        clusterName: local

    elasticsearchConfig:
      hosts:
        - instana-es-http.instana-elasticsearch.svc
      ports: 
        - name: tcp
          port: 9300
        - name: http
          port: 9200
      #properties:
      authEnabled: true
      clusterName: instana
      defaultIndexShards: 5
      defaultIndexReplicas: 0
      defaultIndexRoutingPartitionSize: 2
      #indexConfigs: []

    kafkaConfig:
      hosts:
        - instana-kafka-bootstrap.instana-kafka.svc
      ports: 
        - name: tcp
          port: 9092
      #properties:
      authEnabled: true
      replicationFactor: 1
      # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
      saslMechanism: SCRAM-SHA-512

    beeInstanaConfig:
      hosts:
        - aggregators.beeinstana.svc
      ports:
        - name: tcp
          port: 9998
      #properties:
      authEnabled: true
      clustered: true

    postgresConfigs:
      - hosts:
          - postgres-rw.instana-postgres.svc
        ports:
          - name: tcp
            port: 5432
        #properties: {}
        authEnabled: true
        #databases: []

  componentConfigs:

  deploymentStrategyType: RollingUpdate

  emailConfig:
    smtpConfig:
      from: from@example.com
      host: smtp.example.com
      port: 465
      useSSL: false
      startTLS: false
      check_server_identity: false
    sesConfig:

  serviceProviderConfig:
    basePath: "/auth"
    maxIDPMetadataSizeInBytes: 200000
    maxAuthenticationLifetimeSeconds: 604800

  proxyConfig:

  geoDbUrl:

  agentAcceptorConfig:
    host: agent-acceptor.instana.monitoring.<...>
    port: 443

  featureFlags:
    - name: feature.logging.enabled
      enabled: false
    - name: feature.beeinstana.infra.metrics.enabled
      enabled: false
    - name: feature.infra.smart.alerts.enabled
      enabled: false
    - name: feature.automation.enabled
      enabled: false
    - name: feature.synthetics.enabled
      enabled: false
    - name: feature.kubecost.enabled
      enabled: false
    - name: feature.pcf.enabled
      enabled: false
    - name: feature.vsphere.enabled
      enabled: false
    - name: feature.openstack.enabled
      enabled: false
    - name: feature.phmc.enabled
      enabled: false
    - name: feature.powervc.enabled
      enabled: false
    - name: feature.zhmc.enabled
      enabled: false
    - name: feature.business.observability.enabled
      enabled: false
    - name: feature.assistme.enabled
      enabled: false

  env:

  properties:

  nodeSelector:

  tolerations:

  operationMode: normal
