#
# kafka 391, instana 303
#
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka

metadata:
  name: instana

  labels:
    strimzi.io/cluster: instana

  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft:  enabled

spec:
  kafka:
    version: 3.9.1
    image: kafka-image

    replicas: 1

    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi

    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 50Gi
          deleteClaim: true

    listeners:
      - name: scram
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          useServiceDnsDomain: true

    authorization:
      type: simple
      superUsers:
        - strimzi-kafka-user

    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      max.message.bytes: 52428800
      replica.fetch.max.bytes: 52428800

    template:
      pod:
        tmpDirSizeLimit: 100Mi

  #zookeeper:
  #  replicas: 3
  #  storage:
  #    class: ro_storage_class
  #    type: persistent-claim
  #    size: 5Gi
  #    deleteClaim: true

  entityOperator:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
        # Add the following securityContext snippet for Kubernetes offerings other than OCP.
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
    userOperator:
      image: <internal-image-registry>/operator/strimzi:0.45.0_v0.14.0
