#
# updated to instana version 289
#
apiVersion: instana.io/v1beta2
kind: Unit
metadata:
  namespace: instana-units
  name: tenant0-unit0
spec:
  # Must refer to the namespace of the associated Core object that was created previously
  coreName: instana-core

  # Must refer to the name of the associated Core object that was created previously
  coreNamespace: instana-core

  # the name of the tenant, lowercase
  tenantName: tenant0

  # The name of the unit within the tenant
  unitName: unit0

  # The same rules apply as for Cores. May be ommitted. Default is 'medium'
  resourceProfile: small

  componentConfigs:
  - name: appdata-legacy-converter
    replicas: 3
    resources:
      #limits:
      #  memory: 3962Mi
      requests:
        cpu: 877m
        memory: 3962Mi
  - name: appdata-processor
    replicas: 4
    resources:
      #limits:
      #  memory: 4421Mi
      requests:
        cpu: 1754m
        memory: 4371Mi
  - name: filler
    replicas: 4
    resources:
      #limits:
      #  memory: 4421Mi
      requests:
        cpu: 1754m
        memory: 4371Mi
  - name: issue-tracker
    replicas: 2
    resources:
      #limits:
      #  memory: 2174Mi
      requests:
        cpu: 877m
        memory: 2174Mi
  - name: processor
    replicas: 4
    resources:
      #limits:
      #  memory: 4421Mi
      requests:
        cpu: 1754m
        memory: 4371Mi
  - name: ui-backend
    replicas: 4
    resources:
      #limits:
      #  memory: 2210Mi
      requests:
        cpu: 877m
        memory: 2186Mi
