#
# updated to instana version 289
#
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "instana-zookeeper"
spec:
  # For parameters and default values, see https://github.com/pravega/zookeeper-operator/tree/master/charts/zookeeper#configuration
  replicas: 3
  image:
    repository: <internal-image-registry>/zookeeper
    tag: 3.9.3_v0.16.0
    pullPolicy: IfNotPresent
  pod:
    imagePullSecrets: [name: "<internal-registry-secret>"]
    serviceAccountName: "zookeeper"
    resources:
      requests:
        cpu: 2
        memory: 8Gi
      limits:
        cpu: 2
        memory: 8Gi
    # Add the following securityContext snippet for Kubernetes offerings other than OCP.
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: appng
  config:
    tickTime: 2000
    initLimit: 10
    syncLimit: 5
    maxClientCnxns: 0
    autoPurgeSnapRetainCount: 20
    autoPurgePurgeInterval: 1
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: "10Gi"
      storageClassName: rwo_storageclass
