#!/bin/bash

source ../instana.env
source ./help-functions.sh

source ./certmgr-images.env

ARTIFACT_PUBLIC="artifact-public.instana.io"

MIRROR_HOME=$(get_make_mirror_home)
MIRROR_HOME=${MIRROR_HOME}/${INSTANA_VERSION}

echo writing cert manager image list to $MIRROR_HOME/$CERT_MGR_IMAGE_LIST_FILE

echo "# Certmgr images, Instana version: $INSTANA_VERSION" > ${MIRROR_HOME}/${CERT_MGR_IMAGE_LIST_FILE}

echo "
$CERTMGR_IMG_PLATFORM $ARTIFACT_PUBLIC/$CERTMGR_CAINJECTOR_IMG
$CERTMGR_IMG_PLATFORM $ARTIFACT_PUBLIC/$CERTMGR_CONTROLLER_IMG
$CERTMGR_IMG_PLATFORM $ARTIFACT_PUBLIC/$CERTMGR_WEBHOOK_IMG
$CERTMGR_IMG_PLATFORM $ARTIFACT_PUBLIC/$CERTMGR_ACMESOLVER
$CERTMGR_IMG_PLATFORM $ARTIFACT_PUBLIC/$CERTMGR_CTL_IMG
" >> $MIRROR_HOME/$CERT_MGR_IMAGE_LIST_FILE
